/*representation of pin direction*/
#define PORT_IN  0
#define PORT_OUT 1

/*Port A pins direction*/
#define PORTA_PIN0_DIR PORT_OUT
#define PORTA_PIN1_DIR PORT_OUT
#define PORTA_PIN2_DIR PORT_OUT
#define PORTA_PIN3_DIR PORT_OUT
#define PORTA_PIN4_DIR PORT_OUT
#define PORTA_PIN5_DIR PORT_OUT
#define PORTA_PIN6_DIR PORT_OUT
#define PORTA_PIN7_DIR PORT_OUT

/*Port B pins direction*/
#define PORTB_PIN0_DIR PORT_IN
#define PORTB_PIN1_DIR PORT_IN
#define PORTB_PIN2_DIR PORT_IN
#define PORTB_PIN3_DIR PORT_IN
#define PORTB_PIN4_DIR PORT_IN
#define PORTB_PIN5_DIR PORT_IN
#define PORTB_PIN6_DIR PORT_IN
#define PORTB_PIN7_DIR PORT_IN

/*Port C pins direction*/
#define PORTC_PIN0_DIR PORT_OUT
#define PORTC_PIN1_DIR PORT_OUT
#define PORTC_PIN2_DIR PORT_OUT
#define PORTC_PIN3_DIR PORT_OUT
#define PORTC_PIN4_DIR PORT_OUT
#define PORTC_PIN5_DIR PORT_OUT
#define PORTC_PIN6_DIR PORT_OUT
#define PORTC_PIN7_DIR PORT_OUT

/*Port D pins direction*/
#define PORTD_PIN0_DIR PORT_IN
#define PORTD_PIN1_DIR PORT_IN
#define PORTD_PIN2_DIR PORT_IN
#define PORTD_PIN3_DIR PORT_IN
#define PORTD_PIN4_DIR PORT_IN
#define PORTD_PIN5_DIR PORT_IN
#define PORTD_PIN6_DIR PORT_IN
#define PORTD_PIN7_DIR PORT_IN
